name: Android CI (mavenLocal only)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Gradle build & publish to mavenLocal
        run: |
          echo 'org.gradle.caching=true' >> gradle.properties
          echo 'org.gradle.parallel=true' >> gradle.properties
          echo 'org.gradle.vfs.watch=true' >> gradle.properties
          echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
          ./gradlew publishToMavenLocal --no-daemon --stacktrace
          ./gradlew --stop
        # Untuk mavenLocal, signing nggak wajib → variabel env di bawah bisa dihapus
        # env:
        #   ORG_GRADLE_PROJECT_signingKey: ${{ secrets.maven_pgp_signingKey }}
        #   ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.maven_pgp_signingPassword }}

      - name: Upload local maven repo (optional)
        uses: actions/upload-artifact@v4
        with:
          name: maven-local-repo
          path: ~/.m2/repository/io/github/libxposed
          include-hidden-files: true
          if-no-files-found: warn
